### ISSUE TITLE
Please make repository public

### ISSUE THREAD

**Issue by dcshzj** [sabrinahungxiangyin/CS2102_2021_S1_Team15#43]
Hello, I will be grading your project. Is it possible to change your repository settings to public for the time being? Thank you.

**Comment by sabrinahungxiangyin** [comment]
Hello, I have made the repo public. Thanks!!

**Comment by dcshzj** [comment]
@sabrinahungxiangyin Thank you, I have finished grading your project, so you may set it back to private if you wish.
