### ISSUE TITLE
Difference in contributions

### ISSUE THREAD

**Issue by dcshzj** [sabrinahungxiangyin/CS2102_2021_S1_Team15#44]
Here is the report generated for your project: https://dcshzj.github.io/cs2102-project/ (it also contains other teams that I am grading, so you can look for yours below).

Any reason why there is a large difference in the amount of contributions? For instance, `saranyathiru14` seems to have only made one commit, is there another username that she is contributing under?

Thank you.

**Comment by sabrinahungxiangyin** [comment]
Saranya and Wai Kin both worked on the frontend, and hosted it using Github on other repos! Should we link those as well?

**Comment by dcshzj** [comment]
Ok I got https://github.com/saranyathiru14/cs2102-petowner, any other repositories that your team is working on?

**Comment by thamwaikin** [comment]
Here is the administrator and caretaker frontend: https://github.com/thamwaikin/cs2102-admin

**Comment by dcshzj** [comment]
Okay nice, thanks a lot! I will let you all know if I have questions (probably over the coming week).
